/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package folder;

import Vista.subPanelDashboard.frmInicio;
import java.awt.BorderLayout;

/**
 *
 * @author Hanser Perez
 */
public class frmConsultas extends javax.swing.JFrame {

    /**
     * Creates new form frmDashboard
     */
    public frmConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JPanelContenedor = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVentas = new javax.swing.JMenu();
        jMenuItemFecha = new javax.swing.JMenuItem();
        jMenuItemCaja = new javax.swing.JMenuItem();
        jMenuItemEmpleado = new javax.swing.JMenuItem();
        jMenuItemProducto = new javax.swing.JMenuItem();
        jMenuCompras = new javax.swing.JMenu();
        jMenuCompraFecha = new javax.swing.JMenuItem();
        jMenuCompraEmpleado = new javax.swing.JMenuItem();
        jMenuCompraProveedor = new javax.swing.JMenuItem();
        jMenuCompraProducto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1470, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(661, 661, 661)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(657, 657, 657))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));
        jPanel6.setForeground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPanelContenedorLayout = new javax.swing.GroupLayout(JPanelContenedor);
        JPanelContenedor.setLayout(JPanelContenedorLayout);
        JPanelContenedorLayout.setHorizontalGroup(
            JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelContenedorLayout.createSequentialGroup()
                .addGroup(JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelContenedorLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(334, 334, 334)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelContenedorLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelContenedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 448, Short.MAX_VALUE)
                        .addGroup(JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109))
                    .addGroup(JPanelContenedorLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JPanelContenedorLayout.setVerticalGroup(
            JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelContenedorLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelContenedorLayout.createSequentialGroup()
                .addGroup(JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelContenedorLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelContenedorLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        getContentPane().add(JPanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1470, 540));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jButton4.setBackground(new java.awt.Color(0, 51, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Volver atras");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1339, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 652, 1470, 50));

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 102));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(157, 60));

        jMenuVentas.setText("Ventas");

        jMenuItemFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemFecha.setText("Fecha");
        jMenuItemFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFechaActionPerformed(evt);
            }
        });
        jMenuVentas.add(jMenuItemFecha);

        jMenuItemCaja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemCaja.setText("Caja");
        jMenuItemCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCajaActionPerformed(evt);
            }
        });
        jMenuVentas.add(jMenuItemCaja);

        jMenuItemEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemEmpleado.setText("Empleado");
        jMenuItemEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmpleadoActionPerformed(evt);
            }
        });
        jMenuVentas.add(jMenuItemEmpleado);

        jMenuItemProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemProducto.setText("Producto");
        jMenuItemProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductoActionPerformed(evt);
            }
        });
        jMenuVentas.add(jMenuItemProducto);

        jMenuBar1.add(jMenuVentas);

        jMenuCompras.setText("Compras");

        jMenuCompraFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuCompraFecha.setText("Fecha");
        jMenuCompraFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompraFechaActionPerformed(evt);
            }
        });
        jMenuCompras.add(jMenuCompraFecha);

        jMenuCompraEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuCompraEmpleado.setText("Empleado");
        jMenuCompraEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompraEmpleadoActionPerformed(evt);
            }
        });
        jMenuCompras.add(jMenuCompraEmpleado);

        jMenuCompraProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuCompraProveedor.setText("Proveedor");
        jMenuCompraProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompraProveedorActionPerformed(evt);
            }
        });
        jMenuCompras.add(jMenuCompraProveedor);

        jMenuCompraProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuCompraProducto.setText("Producto");
        jMenuCompraProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompraProductoActionPerformed(evt);
            }
        });
        jMenuCompras.add(jMenuCompraProducto);

        jMenuBar1.add(jMenuCompras);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFechaActionPerformed
        PanelFecha();
    }//GEN-LAST:event_jMenuItemFechaActionPerformed

    private void jMenuItemEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmpleadoActionPerformed
        PanelEmpleado();
    }//GEN-LAST:event_jMenuItemEmpleadoActionPerformed

    private void jMenuItemCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCajaActionPerformed
        PanelCaja();
    }//GEN-LAST:event_jMenuItemCajaActionPerformed

    private void jMenuItemProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductoActionPerformed
        PanelProducto();
    }//GEN-LAST:event_jMenuItemProductoActionPerformed

    private void jMenuCompraFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompraFechaActionPerformed
        PanelFecha();
    }//GEN-LAST:event_jMenuCompraFechaActionPerformed

    private void jMenuCompraEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompraEmpleadoActionPerformed
        PanelEmpleado();

    }//GEN-LAST:event_jMenuCompraEmpleadoActionPerformed

    private void jMenuCompraProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompraProveedorActionPerformed
        PanelProveedores();
    }//GEN-LAST:event_jMenuCompraProveedorActionPerformed

    private void jMenuCompraProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompraProductoActionPerformed
        PanelProducto();
    }//GEN-LAST:event_jMenuCompraProductoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelContenedor;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCompraEmpleado;
    private javax.swing.JMenuItem jMenuCompraFecha;
    private javax.swing.JMenuItem jMenuCompraProducto;
    private javax.swing.JMenuItem jMenuCompraProveedor;
    private javax.swing.JMenu jMenuCompras;
    private javax.swing.JMenuItem jMenuItemCaja;
    private javax.swing.JMenuItem jMenuItemEmpleado;
    private javax.swing.JMenuItem jMenuItemFecha;
    private javax.swing.JMenuItem jMenuItemProducto;
    private javax.swing.JMenu jMenuVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    public void PanelCaja() {

        subPanelCaja caja = new subPanelCaja();
        caja.setSize(1470, 540);
        caja.setLocation(0, 0);

        JPanelContenedor.removeAll();
        JPanelContenedor.add(caja, BorderLayout.CENTER);
        JPanelContenedor.revalidate();
        JPanelContenedor.repaint();
    }

    public void PanelEmpleado() {

        subPanelEmpleado empleado = new subPanelEmpleado();
        empleado.setSize(1470, 540);
        empleado.setLocation(0, 0);

        JPanelContenedor.removeAll();
        JPanelContenedor.add(empleado, BorderLayout.CENTER);
        JPanelContenedor.revalidate();
        JPanelContenedor.repaint();
    }

    public void PanelProducto() {

        subPanelProducto producto = new subPanelProducto();
        producto.setSize(1470, 540);
        producto.setLocation(0, 0);

        JPanelContenedor.removeAll();
        JPanelContenedor.add(producto, BorderLayout.CENTER);
        JPanelContenedor.revalidate();
        JPanelContenedor.repaint();
    }

    public void PanelProveedores() {

        subPanelProveedores proveedores = new subPanelProveedores();
        proveedores.setSize(1470, 540);
        proveedores.setLocation(0, 0);

        JPanelContenedor.removeAll();
        JPanelContenedor.add(proveedores, BorderLayout.CENTER);
        JPanelContenedor.revalidate();
        JPanelContenedor.repaint();
    }

    public void PanelFecha() {

        subPanelfecha fecha = new subPanelfecha();
        fecha.setSize(1470, 540);
        fecha.setLocation(0, 0);

        JPanelContenedor.removeAll();
        JPanelContenedor.add(fecha, BorderLayout.CENTER);
        JPanelContenedor.revalidate();
        JPanelContenedor.repaint();
    }
}
